-- ==============================================================================
-- Relação de colaboradores da fábrica (tabela colaboradores)
-- ==============================================================================
-- Rodar manualmente no Supabase SQL Editor.
--
-- Usada para sugerir o nome do colaborador enquanto se digita (tela de
-- Ocorrências). Os nomes NÃO ficam no código: são carregados por um script
-- de importação à parte, rodado aqui no SQL Editor.
--   - Leitura: qualquer usuário logado.
--   - Cadastro/edição/exclusão: só Coordenação (is_coordinator).
--   - "ativo = false" tira o nome das sugestões sem apagar o histórico.

CREATE TABLE IF NOT EXISTS public.colaboradores (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome text NOT NULL,
  funcao text,
  turno text,
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Mesmo nome não entra duas vezes (sem diferenciar maiúsculas)
CREATE UNIQUE INDEX IF NOT EXISTS colaboradores_nome_unique ON public.colaboradores (upper(nome));

ALTER TABLE public.colaboradores ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated can read colaboradores" ON public.colaboradores;
CREATE POLICY "Authenticated can read colaboradores"
  ON public.colaboradores FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "Coordinator manages colaboradores" ON public.colaboradores;
CREATE POLICY "Coordinator manages colaboradores"
  ON public.colaboradores FOR ALL
  TO authenticated
  USING (public.is_coordinator())
  WITH CHECK (public.is_coordinator());
